import { Router, type IRouter } from "express";
import healthRouter from "./health";
import sweepRouter from "./sweep";
import authRouter from "./auth";
import identityRouter from "./identity";
import invitationsRouter from "./invitations";
import partiesRouter from "./parties";
import consentRouter from "./consent";
import engagementsRouter from "./engagements";
import invoicesRouter from "./invoices";
import recurringRouter from "./recurring";
import verificationRouter from "./verification";
import messagingRouter from "./messaging";
import platformRouter from "./platform";
import operatorRouter from "./operator";
import auditRouter from "./audit";
import advisoryRouter from "./advisory";
import catalogueRouter from "./catalogue";
import smeRouter from "./sme";
import pushRouter from "./push";
import consoleRouter from "./console";
import statementsRouter from "./statements";
import buyerRouter from "./buyer";
import b2cRouter from "./b2c";
import whitelabelRouter from "./whitelabel";
import certificationRouter from "./certification";
import connectorsRouter from "./connectors";
import claimsRouter from "./claims";
import clerkRouter from "./clerk";
// Registers the INT-02 unmapped-code sweep with the pipeline worker.
import "../modules/desk/sweeps";
import "../modules/desk/triage";
import "../modules/clerk/watchdog";
import "../modules/clerk/eval-growth";
import "../modules/clerk/digest";
import "../modules/clerk/client-statement";
import "../modules/clerk/red-team";
import "../modules/clerk/resistance-watch";
import "../modules/push/register";
import "../modules/invoice/register";

const router: IRouter = Router();

router.use(healthRouter);
router.use(sweepRouter);
router.use(authRouter);
router.use(identityRouter);
router.use(invitationsRouter);
router.use(partiesRouter);
router.use(consentRouter);
router.use(engagementsRouter);
router.use(invoicesRouter);
router.use(recurringRouter);
router.use(verificationRouter);
router.use(messagingRouter);
router.use(platformRouter);
router.use(operatorRouter);
router.use(auditRouter);
router.use(advisoryRouter);
router.use(catalogueRouter);
router.use(smeRouter);
router.use(pushRouter);
router.use(consoleRouter);
router.use(statementsRouter);
router.use(buyerRouter);
router.use(b2cRouter);
router.use(whitelabelRouter);
router.use(certificationRouter);
router.use(connectorsRouter);
router.use(claimsRouter);
router.use(clerkRouter);

export default router;
