import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import identityRouter from "./identity";
import partiesRouter from "./parties";
import consentRouter from "./consent";
import engagementsRouter from "./engagements";
import invoicesRouter from "./invoices";
import verificationRouter from "./verification";
import messagingRouter from "./messaging";
import platformRouter from "./platform";
import operatorRouter from "./operator";
import auditRouter from "./audit";
import advisoryRouter from "./advisory";
import catalogueRouter from "./catalogue";
import smeRouter from "./sme";
import consoleRouter from "./console";
import statementsRouter from "./statements";
import buyerRouter from "./buyer";
import b2cRouter from "./b2c";
import whitelabelRouter from "./whitelabel";
import certificationRouter from "./certification";
import connectorsRouter from "./connectors";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(identityRouter);
router.use(partiesRouter);
router.use(consentRouter);
router.use(engagementsRouter);
router.use(invoicesRouter);
router.use(verificationRouter);
router.use(messagingRouter);
router.use(platformRouter);
router.use(operatorRouter);
router.use(auditRouter);
router.use(advisoryRouter);
router.use(catalogueRouter);
router.use(smeRouter);
router.use(consoleRouter);
router.use(statementsRouter);
router.use(buyerRouter);
router.use(b2cRouter);
router.use(whitelabelRouter);
router.use(certificationRouter);
router.use(connectorsRouter);

export default router;
