// Emit the contract version from openapi.yaml (info.version) into both
// generated clients, so the server (@workspace/api-zod) and the web apps
// (@workspace/api-client-react) carry the SAME constant from the SAME build.
// /healthz reports the server's copy; the frontends compare it with theirs
// and show a "stale server build" banner on mismatch. Runs as part of
// codegen, so the CI drift check also guards these files.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const spec = readFileSync(join(here, "openapi.yaml"), "utf8");

// info.version sits before the first top-level `servers:` key; deeper
// `version:` occurrences (schema properties) are indented further.
const infoBlock = spec.split(/^servers:/m)[0];
const match = infoBlock.match(/^ {2}version:\s*(\S+)\s*$/m);
if (!match) {
  console.error("emit-version: could not find info.version in openapi.yaml");
  process.exit(1);
}
const version = match[1];

const contents = `// Generated by lib/api-spec/emit-version.mjs from openapi.yaml info.version.
// Do not edit by hand.
export const API_CONTRACT_VERSION = ${JSON.stringify(version)};
`;

for (const target of [
  join(here, "..", "api-zod", "src", "generated", "version.ts"),
  join(here, "..", "api-client-react", "src", "generated", "version.ts"),
]) {
  writeFileSync(target, contents);
}
console.log(`emit-version: API_CONTRACT_VERSION = ${version}`);
