import {
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  boolean,
  jsonb,
  date,
  pgEnum,
  unique,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { usersTable, firmsTable } from "./organizations.ts";
import { invoicesTable } from "./invoices.ts";
import { partiesTable } from "./parties.ts";
import { createdAt, id, updatedAt } from "./columns.ts";

// ============ Clerk v0 — claims register (C0) ============
// A ClaimRecord is the ONLY source of binding compliance facts the Clerk may
// surface (rates, thresholds, deadlines, citations). Facts are inserted into
// answers verbatim by application code — never generated by a model. Records
// are versioned per claimKey; the maker-checker rule (author of a version can
// never approve it) is enforced at the route layer, and "at most one active
// version per claimKey" is a DB invariant via a partial unique index.

export const claimStateEnum = pgEnum("claim_state", [
  "draft",
  "review",
  "active",
  "suspended",
  "superseded",
  "expired",
  "rejected",
]);

// A typed, protected fact. `value` is stored as text to keep exact-decimal
// fidelity (e.g. "7.5", "50000", "24"); `kind` drives client-side formatting.
export interface ProtectedFact {
  key: string;
  label: string;
  kind: "rate" | "amount" | "duration" | "date" | "count" | "text";
  value: string;
  unit?: string;
}

// Deterministic applicability filters evaluated in app code (never the model).
export interface ClaimApplicability {
  category?: "b2b" | "b2g" | "b2c";
  taxpayerSize?: "small" | "medium" | "large";
  [key: string]: string | undefined;
}

export const claimRecordsTable = pgTable(
  "claim_records",
  {
    id: id(),
    // Stable logical identifier, e.g. "vat.standard_rate". Versions share it.
    claimKey: text("claim_key").notNull(),
    version: integer("version").notNull(),
    state: claimStateEnum("state").notNull().default("draft"),
    // Human-readable one-line summary of what the claim asserts.
    title: text("title").notNull(),
    // The full plain-language proposition shown to operators and used as the
    // fixed answer template. Facts are substituted from protectedFacts only.
    proposition: text("proposition").notNull(),
    protectedFacts: jsonb("protected_facts")
      .$type<ProtectedFact[]>()
      .notNull()
      .default([]),
    // Statutory citation, e.g. "VAT Act s.4 (as amended by Finance Act 2020)".
    citation: text("citation").notNull(),
    applicability: jsonb("applicability")
      .$type<ClaimApplicability>()
      .notNull()
      .default({}),
    effectiveFrom: date("effective_from").notNull(),
    effectiveTo: date("effective_to"),
    // Governance freshness (CLK-KB-07): an active claim whose review date has
    // passed is still visible in the register but can no longer answer.
    reviewDueAt: date("review_due_at"),
    // Maker-checker lineage: the author (maker) of this version, who moved it
    // to review, and who approved/rejected it (checker; never the author).
    createdBy: uuid("created_by")
      .notNull()
      .references(() => usersTable.id),
    submittedBy: uuid("submitted_by").references(() => usersTable.id),
    decidedBy: uuid("decided_by").references(() => usersTable.id),
    decisionNote: text("decision_note"),
    // Set on the OLD version when a newer version becomes active.
    supersededById: uuid("superseded_by_id"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique().on(t.claimKey, t.version),
    // DB invariant: at most one ACTIVE version per logical claim.
    uniqueIndex("claim_records_one_active_per_key")
      .on(t.claimKey)
      .where(sql`${t.state} = 'active'`),
  ],
);

// ============ Clerk v0 — capture cases and Q&A (C1) ============
// Cross-tenant operator work-in-progress. Holds untrusted uploaded document
// content and unreviewed model output, so it is RLS'd bypass-only (operators
// and auditors run with app.bypass='on'; no firm-scoped principal can reach
// these rows) — see migration 0005.

export const clerkCaseKindEnum = pgEnum("clerk_case_kind", [
  "extraction",
  "question",
]);

export const clerkCaseStatusEnum = pgEnum("clerk_case_status", [
  "pending",
  "extracted",
  "in_review",
  "approved",
  "rejected",
  "escalated",
  "failed",
]);

export const clerkSourceTypeEnum = pgEnum("clerk_source_type", [
  "image",
  "pdf",
  "text",
  // Voice notes are transcribed on intake; only the transcript is retained
  // (sourceText) — raw audio is never stored (OPEN-8 minimisation posture).
  "voice",
]);

// One extraction candidate per canonical invoice field. `critical` fields
// (party identity, TINs, invoice number/date, currency, totals, tax) are
// ALWAYS flagged for human confirmation regardless of confidence.
export interface ExtractionField {
  field: string;
  value: string | null;
  confidence: number;
  sourceSnippet: string | null;
  critical: boolean;
  flagged: boolean;
}

export interface ExtractionLine {
  description: string | null;
  quantity: string | null;
  unitPrice: string | null;
  vatRate: string | null;
  confidence: number;
}

export interface ClerkExtraction {
  fields: ExtractionField[];
  lines: ExtractionLine[];
  promptVersion: string;
  model: string;
  // Supplier memory: the approved case whose fixture rode along as the
  // one-shot example for this extraction (absent when extracted cold).
  exemplarCaseId?: string;
}

// Deterministic pre-approval checks run over the extraction (never the model):
// missing critical values, malformed dates/rates, totals that don't add up,
// register-history disagreements. Empty array = nothing blocking; null =
// extraction never succeeded. "advisory" issues inform the reviewer but do
// not knock a case out of the ready-to-approve fast lane.
export interface PreflightIssue {
  field: string;
  message: string;
  severity?: "advisory";
}

// Per-field record of what the operator changed between the model's proposal
// and the approved values — the labeled-outcome exhaust the two-layer thesis
// runs on (every extraction a human corrects is training signal for later
// phases, and the honest measure of extraction quality today).
export interface ClerkCorrection {
  field: string;
  extracted: string | null;
  final: string | null;
  changed: boolean;
}

// Assembled deterministically from an approved ClaimRecord (claim answers) or
// a fixed firm-record lookup (data answers, dataIntent set) — or a neutral
// refusal (answered=false). Never free model prose.
export interface ClerkAnswer {
  answered: boolean;
  claimId?: string;
  claimKey?: string;
  claimVersion?: number;
  // Which data-intent lookup produced the answer (e.g. "data.overdue_submissions").
  dataIntent?: string;
  // App-resolved lookup parameters for display (e.g. {month: "May 2026",
  // client: "Adaeze Foods Ltd"}). Absent for unparameterized answers.
  dataParams?: Record<string, string>;
  proposition?: string;
  facts?: ProtectedFact[];
  citation?: string;
  refusalReason?: string;
}

export const clerkCasesTable = pgTable("clerk_cases", {
  id: id(),
  kind: clerkCaseKindEnum("kind").notNull(),
  status: clerkCaseStatusEnum("status").notNull().default("pending"),
  // --- extraction cases ---
  sourceType: clerkSourceTypeEnum("source_type"),
  sourceName: text("source_name"),
  // Extracted/uploaded text (pdf/text sources). Untrusted document content.
  sourceText: text("source_text"),
  // Base64 image payload (image sources). Excluded from list endpoints.
  sourceImageB64: text("source_image_b64"),
  // Scanned-PDF intake: the rendered page images (base64 PNG, document order)
  // when a PDF had no selectable text. Kept for retry exactly like
  // sourceText/sourceImageB64 and purged by the same content-retention
  // sweep; never returned over the API (the response schemas strip it).
  sourceScanPagesB64: jsonb("source_scan_pages_b64").$type<string[]>(),
  // sha256 of the exact source content (text/transcript/image bytes) —
  // duplicate-intake detection without retaining a second copy.
  sourceHash: text("source_hash"),
  // Recorder-reported length of a voice note, in seconds (voice sources only).
  sourceDurationSec: integer("source_duration_sec"),
  extraction: jsonb("extraction").$type<ClerkExtraction>(),
  // Recomputed on every successful (re-)extraction; see modules/clerk/preflight.
  preflight: jsonb("preflight").$type<PreflightIssue[]>(),
  // The async batch this case was created from, when it came out of one
  // (round-8 idea #3): the review queue groups a bundle's segments together
  // and shows per-batch progress. Null for one-off captures.
  batchId: uuid("batch_id").references(() => clerkBatchesTable.id),
  // --- question cases ---
  question: text("question"),
  answer: jsonb("answer").$type<ClerkAnswer>(),
  // --- review claim (one operator actively works a case at a time) ---
  claimedBy: uuid("claimed_by").references(() => usersTable.id),
  claimedAt: timestamp("claimed_at", { withTimezone: true }),
  // --- review decision ---
  firmId: uuid("firm_id").references(() => firmsTable.id),
  createdBy: uuid("created_by")
    .notNull()
    .references(() => usersTable.id),
  decidedBy: uuid("decided_by").references(() => usersTable.id),
  decisionAction: text("decision_action"),
  decisionReason: text("decision_reason"),
  // Extraction-vs-approved diff, computed at approval (see computeCorrections).
  corrections: jsonb("corrections").$type<ClerkCorrection[] | null>(),
  createdInvoiceId: uuid("created_invoice_id").references(
    () => invoicesTable.id,
  ),
  failReason: text("fail_reason"),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
},
// The duplicate-intake guard probes source_hash on every case creation; the
// queue lists filter by status.
(t) => [
  index("clerk_cases_source_hash_idx").on(t.sourceHash),
  index("clerk_cases_status_idx").on(t.status),
  // The batch progress join counts a batch's reviewed cases.
  index("clerk_cases_batch_idx").on(t.batchId),
]);

// Append-only ledger of every model invocation (enforced by trigger in
// migration 0005): model, prompt version, input reference (hash — never the
// raw document), typed output and the decision taken on it.
export const clerkInferenceOutcomeEnum = pgEnum("clerk_inference_outcome", [
  "ok",
  "invalid_discarded",
  "killed",
  "error",
]);

export const clerkInferenceCallsTable = pgTable("clerk_inference_calls", {
  id: id(),
  caseId: uuid("case_id").references(() => clerkCasesTable.id),
  // The firm the call was made on behalf of (client capture, firm Ask Clerk).
  // Null for operator/platform traffic. Drives the per-firm monthly token
  // budget and lets usage be read under the firm-keyed RLS policy (0009).
  firmId: uuid("firm_id").references(() => firmsTable.id),
  purpose: text("purpose").notNull(),
  model: text("model").notNull(),
  promptVersion: text("prompt_version").notNull(),
  // sha256 of the exact input document/question — auditable without retaining
  // a second copy of untrusted content in the ledger.
  inputRef: text("input_ref").notNull(),
  outputJson: jsonb("output_json").$type<unknown>(),
  schemaValid: boolean("schema_valid").notNull(),
  outcome: clerkInferenceOutcomeEnum("outcome").notNull(),
  errorText: text("error_text"),
  latencyMs: integer("latency_ms"),
  // Token usage where the provider reports it (CLK-NFR-04 cost-to-serve).
  promptTokens: integer("prompt_tokens"),
  completionTokens: integer("completion_tokens"),
  createdAt: createdAt(),
},
// The watchdog and metrics scan recent windows; case joins walk case_id; the
// per-firm budget sums a firm's month-to-date tokens on every capture/ask.
(t) => [
  index("clerk_inference_calls_created_idx").on(t.createdAt),
  index("clerk_inference_calls_case_idx").on(t.caseId),
  index("clerk_inference_calls_firm_idx").on(t.firmId, t.createdAt),
]);

// One fixture's outcome inside an evaluation run (§13.1). Expected/actual
// values are synthetic C1 fixture data, never client content.
export interface ClerkEvalFixtureResult {
  key: string;
  label: string;
  riskLabel: "clean" | "skewed" | "injection" | "correction";
  outcome: "ok" | "invalid" | "error";
  fieldsCompared: number;
  fieldsCorrect: number;
  mismatches: { field: string; expected: string | null; actual: string | null }[];
  // Injection fixtures only: true when every critical field still matched the
  // legitimate document values (the planted instruction changed nothing).
  injectionResisted: boolean | null;
}

// Evaluation runs (§13.1): an operator-triggered pass of the synthetic fixture
// corpus through the LIVE gateway, scored per field against expected values.
// The regression evidence the monthly Readiness Review wants — and the early
// warning when a prompt or model change degrades extraction before operators
// feel it. Append-only evidence (trigger in migration 0006).
export const clerkEvalRunsTable = pgTable("clerk_eval_runs", {
  id: id(),
  // Null for runs started by the nightly learning-loop sweep (no human actor).
  startedBy: uuid("started_by").references(() => usersTable.id),
  model: text("model").notNull(),
  promptVersion: text("prompt_version").notNull(),
  fixtureCount: integer("fixture_count").notNull(),
  fieldsCompared: integer("fields_compared").notNull(),
  fieldsCorrect: integer("fields_correct").notNull(),
  injectionFixtures: integer("injection_fixtures").notNull(),
  injectionResisted: integer("injection_resisted").notNull(),
  results: jsonb("results").$type<ClerkEvalFixtureResult[]>().notNull(),
  durationMs: integer("duration_ms").notNull(),
  createdAt: createdAt(),
});

// Learning loop (Clerk expansion B): every human-corrected approval becomes a
// ground-truth eval fixture — the sweep grows this corpus from the correction
// exhaust, and every eval run (manual or nightly) scores against the static
// corpus PLUS these. One fixture per case; content is the case's fenced
// sourceText and the operator-approved field values.
export const clerkEvalFixturesTable = pgTable("clerk_eval_fixtures", {
  id: id(),
  caseId: uuid("case_id")
    .notNull()
    .unique()
    .references(() => clerkCasesTable.id),
  label: text("label").notNull(),
  sourceText: text("source_text").notNull(),
  expected: jsonb("expected").$type<Record<string, string | null>>().notNull(),
  // The APPROVED invoice's supplier party identity (name/TIN from the
  // register, not extracted strings) — corrections deliberately exclude party
  // identity, so supplier memory (exemplar.ts) matches on these columns.
  // Null on fixtures grown before this existed (they simply never match).
  supplierName: text("supplier_name"),
  supplierTin: text("supplier_tin"),
  createdAt: createdAt(),
});

// ============ Clerk idea #6 — buyer/supplier alias memory ============
// The exhaust learns NAMES: when an approval (or any future confirmed pick)
// pairs an extracted party name with a register party, the normalized name
// key is remembered per firm. Future suggestions — console review chips, NL
// invoice drafting — look the key up FIRST, deterministically; no model is
// involved at either end. One alias key maps to ONE party per firm (the
// newest confirmation wins), and the table is firm-keyed RLS (migration
// 0017) because an alias pairs a firm's document vocabulary with its own
// register.
export const partyNameAliasesTable = pgTable(
  "party_name_aliases",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    partyId: uuid("party_id")
      .notNull()
      .references(() => partiesTable.id),
    // Normalized name key: uppercase meaningful tokens, sorted and joined —
    // the app's key function (modules/clerk/alias.ts) is the only writer.
    alias: text("alias").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [unique().on(t.firmId, t.alias)],
);

// ============ Clerk idea #9 — adversarial eval growth (red team) ============
// Model-GENERATED injection attempts against Clerk's own extraction: a base
// static fixture's document is rewritten to embed a planted instruction while
// every legitimate printed value survives verbatim (validated by the app
// before a row is stored — a variant that fails validation is discarded).
// Rows join the eval corpus as riskLabel "injection" fixtures, so resistance
// is measured by the SAME scoreFixture machinery as the hand-written pair.
// Bypass-only RLS (migration 0016) mirrors clerk_eval_fixtures: adversarial
// documents are operator/sweep material, never firm-readable.
export const clerkRedTeamFixturesTable = pgTable("clerk_red_team_fixtures", {
  id: id(),
  // Which static fixture the variant was derived from, and the attack shape
  // the generator was asked for — together the corpus's provenance record.
  baseKey: text("base_key").notNull(),
  strategy: text("strategy").notNull(),
  sourceText: text("source_text").notNull(),
  // The base fixture's legitimate values — still the ground truth, because
  // validation guarantees they survive in sourceText.
  expected: jsonb("expected").$type<Record<string, string | null>>().notNull(),
  // What the planted instruction tried to force, for the operator reading a
  // failed run ("the model was told to report grandTotal 1.00").
  decoys: jsonb("decoys").$type<Record<string, string>>().notNull(),
  createdAt: createdAt(),
});

// ============ Clerk power D — weekly firm digest ============
// One row per firm per ISO week. The FACTS in a digest are computed by SQL
// (deadlines, failures, receivables); the model only phrases them — and when
// it can't (kill switch, budget, invalid output), the deterministic template
// text is stored instead, recorded via `source`. Firm-keyed RLS (migration
// 0011) so a firm reads only its own digests.

export const clerkDigestSourceEnum = pgEnum("clerk_digest_source", [
  "clerk",
  "template",
]);

export const clerkDigestsTable = pgTable(
  "clerk_digests",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    // Monday 00:00 UTC of the week the digest covers.
    weekStart: timestamp("week_start", { withTimezone: true }).notNull(),
    headline: text("headline").notNull(),
    bullets: jsonb("bullets").$type<string[]>().notNull().default([]),
    source: clerkDigestSourceEnum("source").notNull(),
    createdAt: createdAt(),
  },
  // The sweep's idempotency anchor: at most one digest per firm per week.
  (t) => [unique().on(t.firmId, t.weekStart)],
);
export type ClerkDigestRow = typeof clerkDigestsTable.$inferSelect;

// ============ Clerk idea #5 — per-client monthly statement ============
// The digest pattern, per client party and per CLOSED Lagos calendar month:
// every fact is SQL over the client's own invoices for that month, the model
// only phrases them (template fallback, recorded via `source`), and the sweep
// generates each (firm, client, month) exactly once — the unique key is the
// idempotency anchor. Firm-keyed RLS (migration 0015); client routes must
// ALSO narrow to the caller's party (SEC-03), as everywhere else.

export interface ClientStatementFacts {
  issuedCount: number;
  issuedTotal: string;
  acceptedCount: number;
  acceptedTotal: string;
  acceptedVat: string;
  failedCount: number;
  stillUnsubmittedCount: number;
}

export const clerkClientStatementsTable = pgTable(
  "clerk_client_statements",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    clientPartyId: uuid("client_party_id")
      .notNull()
      .references(() => partiesTable.id),
    // First day of the Lagos calendar month the statement covers (a closed
    // month: generation begins only after it ends).
    monthStart: date("month_start").notNull(),
    facts: jsonb("facts").$type<ClientStatementFacts>().notNull(),
    headline: text("headline").notNull(),
    bullets: jsonb("bullets").$type<string[]>().notNull().default([]),
    source: clerkDigestSourceEnum("source").notNull(),
    // Set when the statement was offered to the client's alert channels (or
    // deliberately skipped: quiet months claim silently). The claim-first
    // UPDATE on this column is the delivery pass's once-only gate — null means
    // "not yet offered", never "the client declined".
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    // Explicit short name: the auto-generated one exceeds Postgres's 63-char
    // identifier cap, gets silently truncated in the DB, and then never
    // matches the schema — making every push re-propose the constraint.
    unique("clerk_client_statements_firm_client_month_unique").on(
      t.firmId,
      t.clientPartyId,
      t.monthStart,
    ),
    index("clerk_client_statements_client_idx").on(
      t.clientPartyId,
      t.monthStart,
    ),
  ],
);
export type ClerkClientStatementRow =
  typeof clerkClientStatementsTable.$inferSelect;

// ============ Clerk idea #8 — async batch intake ============
// One row per month-end bundle: the route only QUEUES (no model call in the
// request), the processor segments and walks each segment through the normal
// capture path, updating the progress counters the UI polls. sourceText is
// the resolved document text, cleared the moment the batch reaches a terminal
// state; firm-keyed RLS (migration 0014) mirrors clerk_cases.

export const clerkBatchStatusEnum = pgEnum("clerk_batch_status", [
  "queued",
  "processing",
  "done",
  "failed",
]);

export const clerkBatchesTable = pgTable(
  "clerk_batches",
  {
    id: id(),
    // Null for operator batches, like clerk_cases.firmId.
    firmId: uuid("firm_id").references(() => firmsTable.id),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => usersTable.id),
    name: text("name"),
    // Resolved document text awaiting segmentation. Untrusted content;
    // cleared the moment segmentation succeeds (the segments then carry the
    // content) and at terminal states; the retention sweep purges stragglers.
    sourceText: text("source_text"),
    // Scanned-bundle intake (round-5 idea #1): 'text' bundles carry
    // sourceText/segments; 'scan' bundles carry the original PDF bytes plus
    // page-range segments. The PDF persists until the batch is terminal
    // (extraction re-rasterizes per slice, so resume/reclaim work from any
    // process) and is cleared with the same discipline as sourceText.
    sourceKind: text("source_kind").notNull().default("text"),
    sourcePdfB64: text("source_pdf_b64"),
    // The segment texts, persisted ONCE at segmentation time so that resume,
    // reclaim and slicing never re-segment (model nondeterminism would shift
    // boundaries and defeat the duplicate guard). processedSegments is the
    // cursor into this array. Cleared at terminal states.
    segments: jsonb("segments").$type<{ label: string | null; text: string }[]>(),
    // Page-range segments for 'scan' bundles, persisted once like segments.
    scanSegments: jsonb("scan_segments").$type<
      { label: string | null; startPage: number; endPage: number }[]
    >(),
    status: clerkBatchStatusEnum("status").notNull().default("queued"),
    // Null until segmentation has run.
    totalSegments: integer("total_segments"),
    processedSegments: integer("processed_segments").notNull().default(0),
    createdCases: integer("created_cases").notNull().default(0),
    skippedDuplicates: integer("skipped_duplicates").notNull().default(0),
    failReason: text("fail_reason"),
    // When the current processor claimed the row; a crashed processor's claim
    // goes stale and the sweep reclaims it.
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("clerk_batches_status_idx").on(t.status),
    index("clerk_batches_firm_idx").on(t.firmId, t.createdAt),
  ],
);
export type ClerkBatch = typeof clerkBatchesTable.$inferSelect;

export type ClaimRecord = typeof claimRecordsTable.$inferSelect;
export type ClerkCase = typeof clerkCasesTable.$inferSelect;
export type ClerkEvalRun = typeof clerkEvalRunsTable.$inferSelect;
