import {
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  boolean,
  jsonb,
  date,
  pgEnum,
  unique,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { usersTable, firmsTable } from "./organizations.ts";
import { invoicesTable } from "./invoices.ts";

// ============ Clerk v0 — claims register (C0) ============
// A ClaimRecord is the ONLY source of binding compliance facts the Clerk may
// surface (rates, thresholds, deadlines, citations). Facts are inserted into
// answers verbatim by application code — never generated by a model. Records
// are versioned per claimKey; the maker-checker rule (author of a version can
// never approve it) is enforced at the route layer, and "at most one active
// version per claimKey" is a DB invariant via a partial unique index.

export const claimStateEnum = pgEnum("claim_state", [
  "draft",
  "review",
  "active",
  "suspended",
  "superseded",
  "expired",
  "rejected",
]);

// A typed, protected fact. `value` is stored as text to keep exact-decimal
// fidelity (e.g. "7.5", "50000", "24"); `kind` drives client-side formatting.
export interface ProtectedFact {
  key: string;
  label: string;
  kind: "rate" | "amount" | "duration" | "date" | "count" | "text";
  value: string;
  unit?: string;
}

// Deterministic applicability filters evaluated in app code (never the model).
export interface ClaimApplicability {
  category?: "b2b" | "b2g" | "b2c";
  taxpayerSize?: "small" | "medium" | "large";
  [key: string]: string | undefined;
}

export const claimRecordsTable = pgTable(
  "claim_records",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Stable logical identifier, e.g. "vat.standard_rate". Versions share it.
    claimKey: text("claim_key").notNull(),
    version: integer("version").notNull(),
    state: claimStateEnum("state").notNull().default("draft"),
    // Human-readable one-line summary of what the claim asserts.
    title: text("title").notNull(),
    // The full plain-language proposition shown to operators and used as the
    // fixed answer template. Facts are substituted from protectedFacts only.
    proposition: text("proposition").notNull(),
    protectedFacts: jsonb("protected_facts")
      .$type<ProtectedFact[]>()
      .notNull()
      .default([]),
    // Statutory citation, e.g. "VAT Act s.4 (as amended by Finance Act 2020)".
    citation: text("citation").notNull(),
    applicability: jsonb("applicability")
      .$type<ClaimApplicability>()
      .notNull()
      .default({}),
    effectiveFrom: date("effective_from").notNull(),
    effectiveTo: date("effective_to"),
    // Maker-checker lineage: the author (maker) of this version, who moved it
    // to review, and who approved/rejected it (checker; never the author).
    createdBy: uuid("created_by")
      .notNull()
      .references(() => usersTable.id),
    submittedBy: uuid("submitted_by").references(() => usersTable.id),
    decidedBy: uuid("decided_by").references(() => usersTable.id),
    decisionNote: text("decision_note"),
    // Set on the OLD version when a newer version becomes active.
    supersededById: uuid("superseded_by_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    unique().on(t.claimKey, t.version),
    // DB invariant: at most one ACTIVE version per logical claim.
    uniqueIndex("claim_records_one_active_per_key")
      .on(t.claimKey)
      .where(sql`${t.state} = 'active'`),
  ],
);

// ============ Clerk v0 — capture cases and Q&A (C1) ============
// Cross-tenant operator work-in-progress. Holds untrusted uploaded document
// content and unreviewed model output, so it is RLS'd bypass-only (operators
// and auditors run with app.bypass='on'; no firm-scoped principal can reach
// these rows) — see migration 0005.

export const clerkCaseKindEnum = pgEnum("clerk_case_kind", [
  "extraction",
  "question",
]);

export const clerkCaseStatusEnum = pgEnum("clerk_case_status", [
  "pending",
  "extracted",
  "in_review",
  "approved",
  "rejected",
  "escalated",
  "failed",
]);

export const clerkSourceTypeEnum = pgEnum("clerk_source_type", [
  "image",
  "pdf",
  "text",
]);

// One extraction candidate per canonical invoice field. `critical` fields
// (party identity, TINs, invoice number/date, currency, totals, tax) are
// ALWAYS flagged for human confirmation regardless of confidence.
export interface ExtractionField {
  field: string;
  value: string | null;
  confidence: number;
  sourceSnippet: string | null;
  critical: boolean;
  flagged: boolean;
}

export interface ExtractionLine {
  description: string | null;
  quantity: string | null;
  unitPrice: string | null;
  vatRate: string | null;
  confidence: number;
}

export interface ClerkExtraction {
  fields: ExtractionField[];
  lines: ExtractionLine[];
  promptVersion: string;
  model: string;
}

// Assembled deterministically from an approved ClaimRecord (answered=true) or
// a neutral refusal (answered=false). Never free model prose.
export interface ClerkAnswer {
  answered: boolean;
  claimId?: string;
  claimKey?: string;
  claimVersion?: number;
  proposition?: string;
  facts?: ProtectedFact[];
  citation?: string;
  refusalReason?: string;
}

export const clerkCasesTable = pgTable("clerk_cases", {
  id: uuid("id").primaryKey().defaultRandom(),
  kind: clerkCaseKindEnum("kind").notNull(),
  status: clerkCaseStatusEnum("status").notNull().default("pending"),
  // --- extraction cases ---
  sourceType: clerkSourceTypeEnum("source_type"),
  sourceName: text("source_name"),
  // Extracted/uploaded text (pdf/text sources). Untrusted document content.
  sourceText: text("source_text"),
  // Base64 image payload (image sources). Excluded from list endpoints.
  sourceImageB64: text("source_image_b64"),
  extraction: jsonb("extraction").$type<ClerkExtraction>(),
  // --- question cases ---
  question: text("question"),
  answer: jsonb("answer").$type<ClerkAnswer>(),
  // --- review decision ---
  firmId: uuid("firm_id").references(() => firmsTable.id),
  createdBy: uuid("created_by")
    .notNull()
    .references(() => usersTable.id),
  decidedBy: uuid("decided_by").references(() => usersTable.id),
  decisionAction: text("decision_action"),
  decisionReason: text("decision_reason"),
  createdInvoiceId: uuid("created_invoice_id").references(
    () => invoicesTable.id,
  ),
  failReason: text("fail_reason"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// Append-only ledger of every model invocation (enforced by trigger in
// migration 0005): model, prompt version, input reference (hash — never the
// raw document), typed output and the decision taken on it.
export const clerkInferenceOutcomeEnum = pgEnum("clerk_inference_outcome", [
  "ok",
  "invalid_discarded",
  "killed",
  "error",
]);

export const clerkInferenceCallsTable = pgTable("clerk_inference_calls", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id").references(() => clerkCasesTable.id),
  purpose: text("purpose").notNull(),
  model: text("model").notNull(),
  promptVersion: text("prompt_version").notNull(),
  // sha256 of the exact input document/question — auditable without retaining
  // a second copy of untrusted content in the ledger.
  inputRef: text("input_ref").notNull(),
  outputJson: jsonb("output_json").$type<unknown>(),
  schemaValid: boolean("schema_valid").notNull(),
  outcome: clerkInferenceOutcomeEnum("outcome").notNull(),
  errorText: text("error_text"),
  latencyMs: integer("latency_ms"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const insertClaimRecordSchema = createInsertSchema(
  claimRecordsTable,
).omit({ id: true, createdAt: true, updatedAt: true });
export const insertClerkCaseSchema = createInsertSchema(clerkCasesTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export const insertClerkInferenceCallSchema = createInsertSchema(
  clerkInferenceCallsTable,
).omit({ id: true, createdAt: true });

export type ClaimRecord = typeof claimRecordsTable.$inferSelect;
export type ClerkCase = typeof clerkCasesTable.$inferSelect;
export type ClerkInferenceCall = typeof clerkInferenceCallsTable.$inferSelect;
export type ClaimState = (typeof claimStateEnum.enumValues)[number];
export type ClerkCaseKind = (typeof clerkCaseKindEnum.enumValues)[number];
export type ClerkCaseStatus = (typeof clerkCaseStatusEnum.enumValues)[number];
export type ClerkSourceType = (typeof clerkSourceTypeEnum.enumValues)[number];
export type ClerkInferenceOutcome =
  (typeof clerkInferenceOutcomeEnum.enumValues)[number];
