import {
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  boolean,
  jsonb,
  date,
  pgEnum,
  unique,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { usersTable, firmsTable } from "./organizations.ts";
import { invoicesTable } from "./invoices.ts";
import { partiesTable } from "./parties.ts";
import { createdAt, id, updatedAt } from "./columns.ts";

// ============ Clerk v0 — claims register (C0) ============
// A ClaimRecord is the ONLY source of binding compliance facts the Clerk may
// surface (rates, thresholds, deadlines, citations). Facts are inserted into
// answers verbatim by application code — never generated by a model. Records
// are versioned per claimKey; the maker-checker rule (author of a version can
// never approve it) is enforced at the route layer, and "at most one active
// version per claimKey" is a DB invariant via a partial unique index.

export const claimStateEnum = pgEnum("claim_state", [
  "draft",
  "review",
  "active",
  "suspended",
  "superseded",
  "expired",
  "rejected",
]);

// A typed, protected fact. `value` is stored as text to keep exact-decimal
// fidelity (e.g. "7.5", "50000", "24"); `kind` drives client-side formatting.
export interface ProtectedFact {
  key: string;
  label: string;
  kind: "rate" | "amount" | "duration" | "date" | "count" | "text";
  value: string;
  unit?: string;
}

// Deterministic applicability filters evaluated in app code (never the model).
export interface ClaimApplicability {
  category?: "b2b" | "b2g" | "b2c";
  taxpayerSize?: "small" | "medium" | "large";
  [key: string]: string | undefined;
}

export const claimRecordsTable = pgTable(
  "claim_records",
  {
    id: id(),
    // Stable logical identifier, e.g. "vat.standard_rate". Versions share it.
    claimKey: text("claim_key").notNull(),
    version: integer("version").notNull(),
    state: claimStateEnum("state").notNull().default("draft"),
    // Human-readable one-line summary of what the claim asserts.
    title: text("title").notNull(),
    // The full plain-language proposition shown to operators and used as the
    // fixed answer template. Facts are substituted from protectedFacts only.
    proposition: text("proposition").notNull(),
    protectedFacts: jsonb("protected_facts")
      .$type<ProtectedFact[]>()
      .notNull()
      .default([]),
    // Statutory citation, e.g. "VAT Act s.4 (as amended by Finance Act 2020)".
    citation: text("citation").notNull(),
    applicability: jsonb("applicability")
      .$type<ClaimApplicability>()
      .notNull()
      .default({}),
    effectiveFrom: date("effective_from").notNull(),
    effectiveTo: date("effective_to"),
    // Governance freshness (CLK-KB-07): an active claim whose review date has
    // passed is still visible in the register but can no longer answer.
    reviewDueAt: date("review_due_at"),
    // Maker-checker lineage: the author (maker) of this version, who moved it
    // to review, and who approved/rejected it (checker; never the author).
    createdBy: uuid("created_by")
      .notNull()
      .references(() => usersTable.id),
    submittedBy: uuid("submitted_by").references(() => usersTable.id),
    decidedBy: uuid("decided_by").references(() => usersTable.id),
    decisionNote: text("decision_note"),
    // Set on the OLD version when a newer version becomes active.
    supersededById: uuid("superseded_by_id"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique().on(t.claimKey, t.version),
    // DB invariant: at most one ACTIVE version per logical claim.
    uniqueIndex("claim_records_one_active_per_key")
      .on(t.claimKey)
      .where(sql`${t.state} = 'active'`),
  ],
);

// ============ Clerk v0 — capture cases and Q&A (C1) ============
// Cross-tenant operator work-in-progress. Holds untrusted uploaded document
// content and unreviewed model output, so it is RLS'd bypass-only (operators
// and auditors run with app.bypass='on'; no firm-scoped principal can reach
// these rows) — see migration 0005.

export const clerkCaseKindEnum = pgEnum("clerk_case_kind", [
  "extraction",
  "question",
  // Notice Desk: a tax-authority notice awaiting review. Same capture rails
  // and review queue as extraction cases, its own proposal column
  // (noticeExtraction) and approve path (creates an obligation, never an
  // invoice). Appended trailing — enum values only ever grow at the end.
  "notice",
]);

export const clerkCaseStatusEnum = pgEnum("clerk_case_status", [
  "pending",
  "extracted",
  "in_review",
  "approved",
  "rejected",
  "escalated",
  "failed",
]);

export const clerkSourceTypeEnum = pgEnum("clerk_source_type", [
  "image",
  "pdf",
  "text",
  // Voice notes are transcribed on intake; only the transcript is retained
  // (sourceText) — raw audio is never stored (OPEN-8 minimisation posture).
  "voice",
]);

// One extraction candidate per canonical invoice field. `critical` fields
// (party identity, TINs, invoice number/date, currency, totals, tax) are
// ALWAYS flagged for human confirmation regardless of confidence.
export interface ExtractionField {
  field: string;
  value: string | null;
  confidence: number;
  sourceSnippet: string | null;
  critical: boolean;
  flagged: boolean;
}

export interface ExtractionLine {
  description: string | null;
  quantity: string | null;
  unitPrice: string | null;
  vatRate: string | null;
  confidence: number;
}

export interface ClerkExtraction {
  fields: ExtractionField[];
  lines: ExtractionLine[];
  promptVersion: string;
  model: string;
  // Supplier memory: the approved case whose fixture rode along as the
  // one-shot example for this extraction (absent when extracted cold).
  exemplarCaseId?: string;
}

// Notice Desk: the proposed reading of a tax-authority notice (kind "notice"
// cases). Reuses the ExtractionField shape — the review UI and corrections
// machinery key on field arrays — but has no lines, and carries the
// model-classified noticeType from the closed catalogue in notice-prompts.ts.
// Proposal only: the obligation row is created by the human approve step.
export interface ClerkNoticeExtraction {
  fields: ExtractionField[];
  noticeType: string;
  promptVersion: string;
  model: string;
}

// Deterministic pre-approval checks run over the extraction (never the model):
// missing critical values, malformed dates/rates, totals that don't add up,
// register-history disagreements. Empty array = nothing blocking; null =
// extraction never succeeded. "advisory" issues inform the reviewer but do
// not knock a case out of the ready-to-approve fast lane.
export interface PreflightIssue {
  field: string;
  message: string;
  severity?: "advisory";
}

// Per-field record of what the operator changed between the model's proposal
// and the approved values — the labeled-outcome exhaust the two-layer thesis
// runs on (every extraction a human corrects is training signal for later
// phases, and the honest measure of extraction quality today).
export interface ClerkCorrection {
  field: string;
  extracted: string | null;
  final: string | null;
  changed: boolean;
}

// Deterministic action link derived from a data answer's own sample rows by
// the app (never the model): names a surface the asker may open. The source
// queries are firm/SEC-03-scoped, so an id here never exceeds the asker's
// own visibility.
export interface ClerkAnswerLink {
  label: string;
  kind: "invoice";
  id: string;
}

// Assembled deterministically from an approved ClaimRecord (claim answers) or
// a fixed firm-record lookup (data answers, dataIntent set) — or a neutral
// refusal (answered=false). Never free model prose.
export interface ClerkAnswer {
  answered: boolean;
  claimId?: string;
  claimKey?: string;
  claimVersion?: number;
  // Which data-intent lookup produced the answer (e.g. "data.overdue_submissions").
  dataIntent?: string;
  // App-resolved lookup parameters for display (e.g. {month: "May 2026",
  // client: "Adaeze Foods Ltd"}). Absent for unparameterized answers.
  dataParams?: Record<string, string>;
  proposition?: string;
  facts?: ProtectedFact[];
  citation?: string;
  refusalReason?: string;
  links?: ClerkAnswerLink[];
}

export const clerkCasesTable = pgTable("clerk_cases", {
  id: id(),
  kind: clerkCaseKindEnum("kind").notNull(),
  status: clerkCaseStatusEnum("status").notNull().default("pending"),
  // --- extraction cases ---
  sourceType: clerkSourceTypeEnum("source_type"),
  sourceName: text("source_name"),
  // Extracted/uploaded text (pdf/text sources). Untrusted document content.
  sourceText: text("source_text"),
  // Base64 image payload (image sources). Excluded from list endpoints.
  sourceImageB64: text("source_image_b64"),
  // Scanned-PDF intake: the rendered page images (base64 PNG, document order)
  // when a PDF had no selectable text. Kept for retry exactly like
  // sourceText/sourceImageB64 and purged by the same content-retention
  // sweep; never returned over the API (the response schemas strip it).
  sourceScanPagesB64: jsonb("source_scan_pages_b64").$type<string[]>(),
  // sha256 of the exact source content (text/transcript/image bytes) —
  // duplicate-intake detection without retaining a second copy.
  sourceHash: text("source_hash"),
  // Recorder-reported length of a voice note, in seconds (voice sources only).
  sourceDurationSec: integer("source_duration_sec"),
  extraction: jsonb("extraction").$type<ClerkExtraction>(),
  // Notice Desk (kind "notice" cases): the proposed notice reading. Mutually
  // exclusive with `extraction` — a case is one document kind for life.
  noticeExtraction: jsonb("notice_extraction").$type<ClerkNoticeExtraction>(),
  // Recomputed on every successful (re-)extraction; see modules/clerk/preflight.
  preflight: jsonb("preflight").$type<PreflightIssue[]>(),
  // The async batch this case was created from, when it came out of one
  // (round-8 idea #3): the review queue groups a bundle's segments together
  // and shows per-batch progress. Null for one-off captures.
  batchId: uuid("batch_id").references(() => clerkBatchesTable.id),
  // --- question cases ---
  question: text("question"),
  answer: jsonb("answer").$type<ClerkAnswer>(),
  // Asker's helpfulness signal on a question case: 'helpful' | 'not_helpful'; null = unrated.
  feedback: text("feedback"),
  // --- review claim (one operator actively works a case at a time) ---
  claimedBy: uuid("claimed_by").references(() => usersTable.id),
  claimedAt: timestamp("claimed_at", { withTimezone: true }),
  // --- review decision ---
  firmId: uuid("firm_id").references(() => firmsTable.id),
  createdBy: uuid("created_by")
    .notNull()
    .references(() => usersTable.id),
  decidedBy: uuid("decided_by").references(() => usersTable.id),
  decisionAction: text("decision_action"),
  decisionReason: text("decision_reason"),
  // Extraction-vs-approved diff, computed at approval (see computeCorrections).
  corrections: jsonb("corrections").$type<ClerkCorrection[] | null>(),
  createdInvoiceId: uuid("created_invoice_id").references(
    () => invoicesTable.id,
  ),
  failReason: text("fail_reason"),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
},
// The duplicate-intake guard probes source_hash on every case creation; the
// queue lists filter by status (the updated_at suffix additionally serves the
// decision-clock scans — quality watch, adoption, avgDecisionMinutes — that
// filter status and read/bucket by updated_at; prefix-compatible with the old
// (status) index); claim-gap mining scans question cases by created_at.
(t) => [
  index("clerk_cases_source_hash_idx").on(t.sourceHash),
  index("clerk_cases_status_idx").on(t.status, t.updatedAt),
  index("clerk_cases_kind_created_idx").on(t.kind, t.createdAt),
  // The batch progress join counts a batch's reviewed cases.
  index("clerk_cases_batch_idx").on(t.batchId),
]);

// Append-only ledger of every model invocation (enforced by trigger in
// migration 0005): model, prompt version, input reference (hash — never the
// raw document), typed output and the decision taken on it.
export const clerkInferenceOutcomeEnum = pgEnum("clerk_inference_outcome", [
  "ok",
  "invalid_discarded",
  "killed",
  "error",
]);

export const clerkInferenceCallsTable = pgTable("clerk_inference_calls", {
  id: id(),
  caseId: uuid("case_id").references(() => clerkCasesTable.id),
  // The firm the call was made on behalf of (client capture, firm Ask Clerk).
  // Null for operator/platform traffic. Drives the per-firm monthly token
  // budget and lets usage be read under the firm-keyed RLS policy (0009).
  firmId: uuid("firm_id").references(() => firmsTable.id),
  purpose: text("purpose").notNull(),
  model: text("model").notNull(),
  promptVersion: text("prompt_version").notNull(),
  // sha256 of the exact input document/question — auditable without retaining
  // a second copy of untrusted content in the ledger.
  inputRef: text("input_ref").notNull(),
  outputJson: jsonb("output_json").$type<unknown>(),
  schemaValid: boolean("schema_valid").notNull(),
  outcome: clerkInferenceOutcomeEnum("outcome").notNull(),
  errorText: text("error_text"),
  latencyMs: integer("latency_ms"),
  // Token usage where the provider reports it (CLK-NFR-04 cost-to-serve).
  promptTokens: integer("prompt_tokens"),
  completionTokens: integer("completion_tokens"),
  createdAt: createdAt(),
},
// The watchdog and metrics scan recent windows; case joins walk case_id; the
// per-firm budget sums a firm's month-to-date tokens on every capture/ask.
(t) => [
  index("clerk_inference_calls_created_idx").on(t.createdAt),
  index("clerk_inference_calls_case_idx").on(t.caseId),
  index("clerk_inference_calls_firm_idx").on(t.firmId, t.createdAt),
]);

// One fixture's outcome inside an evaluation run (§13.1). Expected/actual
// values are synthetic C1 fixture data, never client content.
export interface ClerkEvalFixtureResult {
  key: string;
  label: string;
  riskLabel: "clean" | "skewed" | "injection" | "correction";
  outcome: "ok" | "invalid" | "error";
  fieldsCompared: number;
  fieldsCorrect: number;
  mismatches: { field: string; expected: string | null; actual: string | null }[];
  // Injection fixtures only: true when every critical field still matched the
  // legitimate document values (the planted instruction changed nothing).
  injectionResisted: boolean | null;
}

// Evaluation runs (§13.1): an operator-triggered pass of the synthetic fixture
// corpus through the LIVE gateway, scored per field against expected values.
// The regression evidence the monthly Readiness Review wants — and the early
// warning when a prompt or model change degrades extraction before operators
// feel it. Append-only evidence (trigger in migration 0006).
export const clerkEvalRunsTable = pgTable("clerk_eval_runs", {
  id: id(),
  // Null for runs started by the nightly learning-loop sweep (no human actor).
  startedBy: uuid("started_by").references(() => usersTable.id),
  model: text("model").notNull(),
  promptVersion: text("prompt_version").notNull(),
  fixtureCount: integer("fixture_count").notNull(),
  fieldsCompared: integer("fields_compared").notNull(),
  fieldsCorrect: integer("fields_correct").notNull(),
  injectionFixtures: integer("injection_fixtures").notNull(),
  injectionResisted: integer("injection_resisted").notNull(),
  results: jsonb("results").$type<ClerkEvalFixtureResult[]>().notNull(),
  durationMs: integer("duration_ms").notNull(),
  createdAt: createdAt(),
});

// Intent-classification eval runs (round 15): the Ask classifier's own
// regression lane — a fixed corpus of questions replayed against the LIVE
// intent prompt through the ordinary gateway, scored deterministically
// (classified key === expected key). Bypass-only RLS like the extraction
// runs (migration 0024): operator tooling, no tenant rows.
export interface IntentEvalFixtureResult {
  key: string;
  label: string;
  riskLabel: "clean" | "injection";
  outcome: "ok" | "invalid" | "error";
  classified: { claimKey: string; month: string; client: string } | null;
  correct: boolean;
  // Injection fixtures only: the classifier held the closed-catalogue line.
  resisted: boolean | null;
}

export const clerkIntentEvalRunsTable = pgTable("clerk_intent_eval_runs", {
  id: id(),
  startedBy: uuid("started_by").references(() => usersTable.id),
  model: text("model").notNull(),
  promptVersion: text("prompt_version").notNull(),
  fixtureCount: integer("fixture_count").notNull(),
  correctCount: integer("correct_count").notNull(),
  injectionFixtures: integer("injection_fixtures").notNull(),
  injectionResisted: integer("injection_resisted").notNull(),
  results: jsonb("results").$type<IntentEvalFixtureResult[]>().notNull(),
  durationMs: integer("duration_ms").notNull(),
  createdAt: createdAt(),
});

export type ClerkIntentEvalRun = typeof clerkIntentEvalRunsTable.$inferSelect;

// Grown intent fixtures (round 16): question cases promoted into the intent
// eval corpus with the question text SCRUBBED (engaged-client names mapped
// onto the frozen synthetic directory). Operator tooling — bypass-only RLS
// (migration 0025) like the runs table; a retired fixture stays as evidence
// but leaves the corpus loaders.
export const clerkIntentFixturesTable = pgTable("clerk_intent_fixtures", {
  id: id(),
  caseId: uuid("case_id")
    .notNull()
    .unique()
    .references(() => clerkCasesTable.id),
  label: text("label").notNull(),
  question: text("question").notNull(),
  expected: jsonb("expected")
    .$type<{ claimKey: string; month?: string; client?: string }>()
    .notNull(),
  retiredAt: timestamp("retired_at", { withTimezone: true }),
  createdAt: createdAt(),
});

export type ClerkIntentFixture = typeof clerkIntentFixturesTable.$inferSelect;

// Learning loop (Clerk expansion B): every human-corrected approval becomes a
// ground-truth eval fixture — the sweep grows this corpus from the correction
// exhaust, and every eval run (manual or nightly) scores against the static
// corpus PLUS these. One fixture per case; content is the case's fenced
// sourceText and the operator-approved field values.
export const clerkEvalFixturesTable = pgTable("clerk_eval_fixtures", {
  id: id(),
  caseId: uuid("case_id")
    .notNull()
    .unique()
    .references(() => clerkCasesTable.id),
  // Which extraction lane the fixture exercises: 'invoice' (the historic
  // corpus) or 'notice' (round 30 — grown from approved authority-notice
  // cases; scored against NOTICE_FIELDS by the runner's notice branch).
  // Text, not an enum: the document domains grow.
  kind: text("kind").notNull().default("invoice"),
  label: text("label").notNull(),
  sourceText: text("source_text").notNull(),
  expected: jsonb("expected").$type<Record<string, string | null>>().notNull(),
  // The APPROVED invoice's supplier party identity (name/TIN from the
  // register, not extracted strings) — corrections deliberately exclude party
  // identity, so supplier memory (exemplar.ts) matches on these columns.
  // Null on fixtures grown before this existed (they simply never match).
  supplierName: text("supplier_name"),
  supplierTin: text("supplier_tin"),
  // Corpus curation (round 15): a retired fixture stays as evidence (its runs
  // remain interpretable) but is excluded from every corpus loader BEFORE the
  // newest-N cap, so retirement frees a corpus slot. Null = in the corpus.
  retiredAt: timestamp("retired_at", { withTimezone: true }),
  createdAt: createdAt(),
});

// ============ Clerk idea #6 — buyer/supplier alias memory ============
// The exhaust learns NAMES: when an approval (or any future confirmed pick)
// pairs an extracted party name with a register party, the normalized name
// key is remembered per firm. Future suggestions — console review chips, NL
// invoice drafting — look the key up FIRST, deterministically; no model is
// involved at either end. One alias key maps to ONE party per firm (the
// newest confirmation wins), and the table is firm-keyed RLS (migration
// 0017) because an alias pairs a firm's document vocabulary with its own
// register.
export const partyNameAliasesTable = pgTable(
  "party_name_aliases",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    partyId: uuid("party_id")
      .notNull()
      .references(() => partiesTable.id),
    // Normalized name key: uppercase meaningful tokens, sorted and joined —
    // the app's key function (modules/clerk/alias.ts) is the only writer.
    alias: text("alias").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [unique().on(t.firmId, t.alias)],
);

// ============ Clerk idea #9 — adversarial eval growth (red team) ============
// Model-GENERATED injection attempts against Clerk's own extraction: a base
// static fixture's document is rewritten to embed a planted instruction while
// every legitimate printed value survives verbatim (validated by the app
// before a row is stored — a variant that fails validation is discarded).
// Rows join the eval corpus as riskLabel "injection" fixtures, so resistance
// is measured by the SAME scoreFixture machinery as the hand-written pair.
// Bypass-only RLS (migration 0016) mirrors clerk_eval_fixtures: adversarial
// documents are operator/sweep material, never firm-readable.
export const clerkRedTeamFixturesTable = pgTable("clerk_red_team_fixtures", {
  id: id(),
  // Which static fixture the variant was derived from, and the attack shape
  // the generator was asked for — together the corpus's provenance record.
  baseKey: text("base_key").notNull(),
  strategy: text("strategy").notNull(),
  sourceText: text("source_text").notNull(),
  // The base fixture's legitimate values — still the ground truth, because
  // validation guarantees they survive in sourceText.
  expected: jsonb("expected").$type<Record<string, string | null>>().notNull(),
  // What the planted instruction tried to force, for the operator reading a
  // failed run ("the model was told to report grandTotal 1.00").
  decoys: jsonb("decoys").$type<Record<string, string>>().notNull(),
  // Corpus curation (round 15): same posture as clerk_eval_fixtures.retiredAt
  // — a retired variant is excluded from the loaders before the cap, so a
  // stale or low-value attack stops costing one model call per eval run.
  retiredAt: timestamp("retired_at", { withTimezone: true }),
  createdAt: createdAt(),
});

// ============ Clerk power D — weekly firm digest ============
// One row per firm per ISO week. The FACTS in a digest are computed by SQL
// (deadlines, failures, receivables); the model only phrases them — and when
// it can't (kill switch, budget, invalid output), the deterministic template
// text is stored instead, recorded via `source`. Firm-keyed RLS (migration
// 0011) so a firm reads only its own digests.

export const clerkDigestSourceEnum = pgEnum("clerk_digest_source", [
  "clerk",
  "template",
]);

export const clerkDigestsTable = pgTable(
  "clerk_digests",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    // Monday 00:00 UTC of the week the digest covers.
    weekStart: timestamp("week_start", { withTimezone: true }).notNull(),
    headline: text("headline").notNull(),
    bullets: jsonb("bullets").$type<string[]>().notNull().default([]),
    source: clerkDigestSourceEnum("source").notNull(),
    // The fact snapshot the digest phrased (round 20): consecutive weekly
    // snapshots are the digest-impact report's time series — the only way
    // to know what the book looked like when each digest went out. Null on
    // rows generated before the column existed; the report skips those.
    facts: jsonb("facts").$type<Record<string, unknown> | null>(),
    // Set when the digest was offered to the firm's opted-in staff channels
    // (or deliberately skipped: no opted-in recipients claims silently —
    // opt-in means quiet is correct). The claim-first UPDATE on this column
    // is the delivery pass's once-only gate, mirroring
    // clerk_client_statements.delivered_at — null means "not yet offered".
    // The GET /clerk/digest response schema strips it (plain zod object).
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    createdAt: createdAt(),
  },
  // The sweep's idempotency anchor: at most one digest per firm per week.
  (t) => [unique().on(t.firmId, t.weekStart)],
);
export type ClerkDigestRow = typeof clerkDigestsTable.$inferSelect;

// ============ Clerk idea #5 — per-client monthly statement ============
// The digest pattern, per client party and per CLOSED Lagos calendar month:
// every fact is SQL over the client's own invoices for that month, the model
// only phrases them (template fallback, recorded via `source`), and the sweep
// generates each (firm, client, month) exactly once — the unique key is the
// idempotency anchor. Firm-keyed RLS (migration 0015); client routes must
// ALSO narrow to the caller's party (SEC-03), as everywhere else.

export interface ClientStatementFacts {
  issuedCount: number;
  issuedTotal: string;
  acceptedCount: number;
  acceptedTotal: string;
  acceptedVat: string;
  failedCount: number;
  stillUnsubmittedCount: number;
}

export const clerkClientStatementsTable = pgTable(
  "clerk_client_statements",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    clientPartyId: uuid("client_party_id")
      .notNull()
      .references(() => partiesTable.id),
    // First day of the Lagos calendar month the statement covers (a closed
    // month: generation begins only after it ends).
    monthStart: date("month_start").notNull(),
    facts: jsonb("facts").$type<ClientStatementFacts>().notNull(),
    headline: text("headline").notNull(),
    bullets: jsonb("bullets").$type<string[]>().notNull().default([]),
    source: clerkDigestSourceEnum("source").notNull(),
    // Set when the statement was offered to the client's alert channels (or
    // deliberately skipped: quiet months claim silently). The claim-first
    // UPDATE on this column is the delivery pass's once-only gate — null means
    // "not yet offered", never "the client declined".
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    // Explicit short name: the auto-generated one exceeds Postgres's 63-char
    // identifier cap, gets silently truncated in the DB, and then never
    // matches the schema — making every push re-propose the constraint.
    unique("clerk_client_statements_firm_client_month_unique").on(
      t.firmId,
      t.clientPartyId,
      t.monthStart,
    ),
    index("clerk_client_statements_client_idx").on(
      t.clientPartyId,
      t.monthStart,
    ),
    // The delivery pass scans undelivered rows oldest-first every sweep;
    // partial so the scan never touches the ever-growing delivered majority.
    index("clerk_client_statements_undelivered_idx")
      .on(t.createdAt)
      .where(sql`delivered_at IS NULL`),
  ],
);
export type ClerkClientStatementRow =
  typeof clerkClientStatementsTable.$inferSelect;

// ============ Clerk idea #8 — async batch intake ============
// One row per month-end bundle: the route only QUEUES (no model call in the
// request), the processor segments and walks each segment through the normal
// capture path, updating the progress counters the UI polls. sourceText is
// the resolved document text, cleared the moment the batch reaches a terminal
// state; firm-keyed RLS (migration 0014) mirrors clerk_cases.

export const clerkBatchStatusEnum = pgEnum("clerk_batch_status", [
  "queued",
  "processing",
  "done",
  "failed",
]);

export const clerkBatchesTable = pgTable(
  "clerk_batches",
  {
    id: id(),
    // Null for operator batches, like clerk_cases.firmId.
    firmId: uuid("firm_id").references(() => firmsTable.id),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => usersTable.id),
    name: text("name"),
    // Resolved document text awaiting segmentation. Untrusted content;
    // cleared the moment segmentation succeeds (the segments then carry the
    // content) and at terminal states; the retention sweep purges stragglers.
    sourceText: text("source_text"),
    // Scanned-bundle intake (round-5 idea #1): 'text' bundles carry
    // sourceText/segments; 'scan' bundles carry the original PDF bytes plus
    // page-range segments. The PDF persists until the batch is terminal
    // (extraction re-rasterizes per slice, so resume/reclaim work from any
    // process) and is cleared with the same discipline as sourceText.
    sourceKind: text("source_kind").notNull().default("text"),
    sourcePdfB64: text("source_pdf_b64"),
    // The segment texts, persisted ONCE at segmentation time so that resume,
    // reclaim and slicing never re-segment (model nondeterminism would shift
    // boundaries and defeat the duplicate guard). processedSegments is the
    // cursor into this array. Cleared at terminal states.
    segments: jsonb("segments").$type<{ label: string | null; text: string }[]>(),
    // Page-range segments for 'scan' bundles, persisted once like segments.
    scanSegments: jsonb("scan_segments").$type<
      { label: string | null; startPage: number; endPage: number }[]
    >(),
    status: clerkBatchStatusEnum("status").notNull().default("queued"),
    // Null until segmentation has run.
    totalSegments: integer("total_segments"),
    processedSegments: integer("processed_segments").notNull().default(0),
    createdCases: integer("created_cases").notNull().default(0),
    skippedDuplicates: integer("skipped_duplicates").notNull().default(0),
    failReason: text("fail_reason"),
    // When the current processor claimed the row; a crashed processor's claim
    // goes stale and the sweep reclaims it.
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("clerk_batches_status_idx").on(t.status),
    index("clerk_batches_firm_idx").on(t.firmId, t.createdAt),
  ],
);
export type ClerkBatch = typeof clerkBatchesTable.$inferSelect;

export type ClaimRecord = typeof claimRecordsTable.$inferSelect;
export type ClerkCase = typeof clerkCasesTable.$inferSelect;
export type ClerkEvalRun = typeof clerkEvalRunsTable.$inferSelect;

// Phrasing eval runs (round 18): the digest/chaser fixture corpora replayed
// through the BYTE-IDENTICAL production prompt builders and scored
// deterministically — grounding (no novel numeral), required mentions,
// forbidden content, injection resistance. Operator tooling with no tenant
// reads — bypass-only RLS (migration 0027), the intent-eval runs posture.
export interface PhrasingEvalFixtureResult {
  key: string;
  surface: string;
  label: string;
  riskLabel: "clean" | "injection";
  outcome: "ok" | "invalid" | "error";
  grounded: boolean | null;
  correct: boolean;
  resisted: boolean | null;
  failures: string[];
}

export const clerkPhrasingEvalRunsTable = pgTable("clerk_phrasing_eval_runs", {
  id: id(),
  startedBy: uuid("started_by").references(() => usersTable.id),
  model: text("model").notNull(),
  // Per-surface prompt versions at run time, e.g. {digest: "digest.v6",
  // chaser: "chaser.v3"} — the trend must know which prompts it measured.
  promptVersions: jsonb("prompt_versions")
    .$type<Record<string, string>>()
    .notNull(),
  fixtureCount: integer("fixture_count").notNull(),
  correctCount: integer("correct_count").notNull(),
  groundedCount: integer("grounded_count").notNull(),
  injectionFixtures: integer("injection_fixtures").notNull(),
  injectionResisted: integer("injection_resisted").notNull(),
  results: jsonb("results").$type<PhrasingEvalFixtureResult[]>().notNull(),
  durationMs: integer("duration_ms").notNull(),
  createdAt: createdAt(),
});

export type ClerkPhrasingEvalRun = typeof clerkPhrasingEvalRunsTable.$inferSelect;

// Standing approvals (round 28): a durable, revocable GRANT that lets the
// daily sweep run one action kind for one client without a fresh per-batch
// approval. The grant names who approved it (and their role at grant time,
// so the sweep can re-check they'd STILL be allowed to approve today), caps
// how many targets a single run may touch, and carries its own lifecycle:
// paused (reversible — by a human or by the sweep's own tripwires) versus
// revoked (permanent evidence; a partial unique index keeps at most one
// LIVE grant per firm/client/kind while revoked rows pile up as history).
// lastRunDay is the Lagos-calendar claim cell: the sweep CASes today's date
// into it before executing, so concurrent instances can never double-run a
// policy. Firm-keyed RLS via migration 0029.
export const clerkActionPoliciesTable = pgTable(
  "clerk_action_policies",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    clientPartyId: uuid("client_party_id")
      .notNull()
      .references(() => partiesTable.id),
    // A key from POLICY_KINDS (modules/clerk/action-policies.ts) — the
    // automatable subset of the action catalogue. Text so old rows survive
    // catalogue growth.
    kind: text("kind").notNull(),
    // Per-run target cap, chosen at grant time (1..MAX_ACTION_TARGETS).
    maxTargetsPerRun: integer("max_targets_per_run").notNull(),
    grantedBy: uuid("granted_by")
      .notNull()
      .references(() => usersTable.id),
    // The grantor's role at grant time; the sweep re-derives their CURRENT
    // membership and pauses the policy if approval rights lapsed.
    grantedByRole: text("granted_by_role").notNull(),
    pausedAt: timestamp("paused_at", { withTimezone: true }),
    // "manual" for a human pause; the sweep's tripwires write
    // "grantor_inactive" | "consent_missing" | "failed_targets".
    pausedReason: text("paused_reason"),
    // Null when the sweep paused it (pausedReason says why).
    pausedBy: uuid("paused_by").references(() => usersTable.id),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: uuid("revoked_by").references(() => usersTable.id),
    lastRunAt: timestamp("last_run_at", { withTimezone: true }),
    // Lagos YYYY-MM-DD of the last claimed run — the once-per-day CAS cell.
    lastRunDay: text("last_run_day"),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex("clerk_action_policies_live_uq")
      .on(t.firmId, t.clientPartyId, t.kind)
      .where(sql`revoked_at IS NULL`),
    index("clerk_action_policies_scope_idx").on(t.firmId, t.clientPartyId),
  ],
);

export type ClerkActionPolicy = typeof clerkActionPoliciesTable.$inferSelect;

// Proposed actions (round 21): the durable APPROVAL artifact. Proposals
// themselves are never stored — they are computed live from the detectors,
// so they can never be stale — but the moment a human APPROVES a batch,
// this row records who decided, on what evidence (the facts the card
// showed), over which targets, and what the platform's own execution path
// then did per invoice. Firm-keyed RLS via migration 0028.
export interface ActionTargetOutcome {
  invoiceId: string;
  invoiceNumber: string;
  // "drafted" is the draft_chasers success outcome (round 22): a reminder
  // was written for the human to send — nothing was submitted anywhere.
  outcome: "submitted" | "invalid" | "skipped_not_eligible" | "failed" | "drafted";
  error: string | null;
}

export const clerkActionDecisionsTable = pgTable(
  "clerk_action_decisions",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    clientPartyId: uuid("client_party_id")
      .notNull()
      .references(() => partiesTable.id),
    // A key from the closed action catalogue (modules/clerk/actions.ts) —
    // stored as text so old rows survive catalogue growth.
    kind: text("kind").notNull(),
    decidedBy: uuid("decided_by")
      .notNull()
      .references(() => usersTable.id),
    // Round 28: set when a standing approval (not a fresh human click)
    // authorized this run — decidedBy then names the policy's GRANTOR.
    // Null for every hand-approved batch.
    policyId: uuid("policy_id").references(() => clerkActionPoliciesTable.id),
    // Round 32: set when a plan run's step executed this batch — the run's
    // whole-plan approval is the authorization, decidedBy its approver.
    // Null for hand and policy batches. (Lazy reference: the plan-runs
    // table is declared later in this file.)
    planRunId: uuid("plan_run_id").references(() => clerkPlanRunsTable.id),
    // The facts the approval surface showed at decision time.
    evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull(),
    targets: jsonb("targets").$type<ActionTargetOutcome[]>().notNull(),
    requestedCount: integer("requested_count").notNull(),
    executedCount: integer("executed_count").notNull(),
    skippedCount: integer("skipped_count").notNull(),
    failedCount: integer("failed_count").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    index("clerk_action_decisions_scope_idx").on(
      t.firmId,
      t.clientPartyId,
      t.createdAt,
    ),
  ],
);

export type ClerkActionDecision =
  typeof clerkActionDecisionsTable.$inferSelect;

// ============ Do with Clerk Phase 2 — plan runs (round 32) ============
// One row per approved multi-step action plan: the whole-plan approval
// freezes the steps SERVER-SIDE (from an Ask case's action sections, or a
// deterministic template) and the pipeline worker executes them in order,
// one step per slice, through the ordinary executeAction path — every step
// lands its own decision-ledger row, and the run records which. The batch
// processor's claim/fence discipline applies verbatim: status CAS +
// claimedAt heartbeat, stale claims reclaimed by the sweep. A step whose
// failures cross the autopilot's half-rule HALTS the run (remaining steps
// skipped, reason recorded) — a plan is a sequence, not a scattergun.

export const clerkPlanRunStatusEnum = pgEnum("clerk_plan_run_status", [
  "queued",
  "running",
  "done",
  "halted",
  "failed",
]);

export interface PlanRunStep {
  kind: string;
  clientPartyId: string;
  clientName: string;
  // The approved target ids, frozen at approval; executeAction re-validates
  // every one at execution time (already-submitted paper skips honestly).
  // Empty for deterministic step kinds, whose targets are not invoices.
  invoiceIds: string[];
  // Deterministic-step targets (round 34, Close with Clerk): the
  // "buyerPartyId:currency" pairs a draft_recurring step was approved for
  // — the miner's own grouping, so a buyer billed in two currencies is two
  // distinct targets — frozen at approval; execution re-mines and only
  // drafts pairs still unbilled. Absent on action steps and on rows
  // written before round 34.
  buyerTargets?: string[];
  // reconcile_matches targets (round 35): the frozen high-confidence
  // match-proposal ids; execution re-validates each is still proposed and
  // above the autopilot threshold before accepting. Absent elsewhere.
  proposalTargets?: string[];
  // Evidence of a deterministic step's writes: the draft invoices it
  // created (pointers only). Absent on action steps and pre-34 rows.
  draftIds?: string[];
  status: "pending" | "executed" | "halted_here" | "skipped";
  // The decision-ledger row this step's execution wrote (null until run,
  // for skipped steps, and always for deterministic steps — their ledger
  // is the created rows themselves plus the run's own audit).
  decisionId: string | null;
  executedCount: number;
  failedCount: number;
  skippedCount: number;
}

export const clerkPlanRunsTable = pgTable(
  "clerk_plan_runs",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    // The Ask case whose action sections were approved (null for template
    // runs — they have no conversational origin).
    caseId: uuid("case_id").references(() => clerkCasesTable.id),
    // The deterministic template that assembled this run (null for ask
    // runs). Text, not an enum: the registry grows in code.
    templateKey: text("template_key"),
    status: clerkPlanRunStatusEnum("status").notNull().default("queued"),
    steps: jsonb("steps").$type<PlanRunStep[]>().notNull(),
    // The cursor: steps[0..processedSteps) are settled.
    processedSteps: integer("processed_steps").notNull().default(0),
    // Why the run stopped early (tripwire text), null otherwise.
    haltReason: text("halt_reason"),
    // Who approved the whole plan — the actor every step's decision row
    // names, re-validated (current membership still carries each kind's
    // capability) just before each step executes.
    approvedBy: uuid("approved_by")
      .notNull()
      .references(() => usersTable.id),
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("clerk_plan_runs_status_idx").on(t.status),
    index("clerk_plan_runs_firm_idx").on(t.firmId, t.createdAt),
    // One LIVE run per case (round-32 review m7): a double-click or two
    // approvers minting concurrent runs over the same frozen steps resolve
    // on this instead of double-executing; terminal runs free the slot.
    uniqueIndex("clerk_plan_runs_live_case_uq")
      .on(t.caseId)
      .where(sql`status IN ('queued', 'running') AND case_id IS NOT NULL`),
  ],
);

export type ClerkPlanRun = typeof clerkPlanRunsTable.$inferSelect;

// ============ Do with Clerk Phase 3 — recurring plan policies (round 33) ==
// A standing approval of a TEMPLATE per client: once per closed Lagos month
// the sweep assembles and runs it as an ordinary plan run under the
// grantor's re-validated authority. Same lifecycle spine as
// clerk_action_policies (pause/revoke, tripwire auto-pause when the linked
// run halts); the month claim CAS on lastRunMonth is the once-only gate.

export const clerkPlanPoliciesTable = pgTable(
  "clerk_plan_policies",
  {
    id: id(),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id),
    clientPartyId: uuid("client_party_id")
      .notNull()
      .references(() => partiesTable.id),
    templateKey: text("template_key").notNull(),
    grantedBy: uuid("granted_by")
      .notNull()
      .references(() => usersTable.id),
    grantedByRole: text("granted_by_role").notNull(),
    pausedAt: timestamp("paused_at", { withTimezone: true }),
    pausedReason: text("paused_reason"),
    pausedBy: uuid("paused_by").references(() => usersTable.id),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: uuid("revoked_by").references(() => usersTable.id),
    // The once-per-month CAS gate (Lagos "YYYY-MM") and the run it minted.
    lastRunMonth: text("last_run_month"),
    lastRunId: uuid("last_run_id").references(() => clerkPlanRunsTable.id),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex("clerk_plan_policies_live_uq")
      .on(t.firmId, t.clientPartyId, t.templateKey)
      .where(sql`revoked_at IS NULL`),
    index("clerk_plan_policies_scope_idx").on(t.firmId, t.clientPartyId),
  ],
);

export type ClerkPlanPolicy = typeof clerkPlanPoliciesTable.$inferSelect;
